### ISSUE TITLE
[Meta] UI Manifest

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-multi-user#173]
# Bouton upload Manifest
-  Detection du nombre de canvas
- Detection de la taille du media 
- Synchroniser description et title avec description et name
# General UI
- UI = MediaCard UI 

# Bouton create Manifest
- Use this manifest as a model :https://files.tetras-libre.fr/dev/test-vertical-video.json
- Synchroniser description et title avec description et name
- Avoir un menu drag and drop pour faire switch les canvas : https://mui.com/x/react-data-grid/style-recipes/#remove-drag-handle-for-columns-that-are-not-resizeable
- Avoir un side panel comme sur le site canva.com pour ajouter les media (recherche par tag et par bar de recherche)

**Comment by Drilio** [comment]
- [ ] The image used by the manifest card must be the thumbmail or a placeholder, remove the logic that use the first manifest image if there is no thumbmail. 
- [ ] Medias avec un S dans l'onglet
- [ ] Projet > Manifest > Media dans cette ordre dans le menu de gauche
- [ ] Pouvoir créer des manifests a partir d'URL exposer sur internet 'External link' 
- [ ] Panel media dans la création de manifest, il faut une barre de recherche et voir le nom des médias
- [ ] Création de manifest avec un "dial" Material UI
