### ISSUE TITLE
[ META ] General Refacto

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-multi-user#196]
- [x] SCENE-CE/mirador-annotation-editor#104
- [x] SCENE-CE/mirador-multi-user#195
- [ ] SCENE-CE/mirador-multi-user#197
- [ ] SCENE-CE/mirador-multi-user#198
