### ISSUE TITLE
[META] Backend Important stuff to do

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-multi-user#222]
To do : 
- [x] Authorization factory 2
- [x] Auth Guard sur toutes les routes 1
- [x] #302
- [x] Rôle API User 2
- [x] Du front end je dois partager medias/groups/projects/manifest UNIQUEMENT a partir du pseudo utilisateur 1 
- [x] #248
- [x] Capcha [218](#218) 2

**Comment by Drilio** [comment]
Project rights is now share with updateProject and it need whole user and project, this must be split into two different routes and must not need user entity, just id.
