### ISSUE TITLE
[Meta] Add video support on MMU

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-multi-user#295]
- [x] User can upload a vidéo with youtube link or peertube link 
- [x] Display medias with three tabs video | image | all 
- [x] Change manifest creation to support video
