### ISSUE TITLE
TODO : 15/11

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-multi-user#300]
- [x] Snapshot mettre tous les boutons à droite
- [x] Mettre une alerte si l'utilisateur essaye de copier le snapShot alors qu'il n'a pas été créé
- [x] Link media doit ouvrir l'edit modal
- [x] ajouter un icon pour identifier les medias dans le side panel
- [x] Retour utilisateur quand il upload un mauvais format et si c'est une vidéo un petit message pour dire d'utiliser youtube ou peertube
