### ISSUE TITLE
META - Missing issues

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-multi-user#310]
MMU @Drilio 

- [x] Admin role on the platform SCENE-CE/mirador-multi-user#302 
- [x] Lock project during editing SCENE-CE/mirador-multi-user#305 
- [x] Advanced manifest editor SCENE-CE/mirador-multi-user#178 
- [x] Finish Metadata
- [x] Add duration on manifest video creation : NEED to BE PRECISED

MV @geourjoa 

- [x] Seeko to issue https://github.com/SCENE-CE/mirador-video/issues/9
- [x] Annotate audio

MAE/ MAEV @geourjoa 

- [ ] SCENE-CE/mirador-annotation-editor#130
- [x] https://github.com/SCENE-CE/mirador-annotation-editor-video/issues/4
- [x] Some annotation template are not working
- [x] Complex annotation
- [x] Annotate Audio

Annotation server 

- [x] CRUD server annotation @Drilio 
- [x] MMUStorageAdapter @geourjoa 

Peertube @EL 

- [x] EL ?

Prod :

- Deploy everuthing on Humanum
   - MMU : domain name must be precised
   - Peertube : domain name must be precised 
   - Admin mail to receivve platform error
   - Domain name configuration
