### ISSUE TITLE
[Meta]  Gestion des médias

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-multi-user#50]
WIP Architecture

Les médias sont des fichiers audios / videos / images.

LECTURE

Les médias seront stocké sur le système de fichier et servis par un caddy qui les exposera en lecture sans limitations sur le web.
Chacun des médias sera contenus dans un dossier avec un nom sous la forme d'un hash long. 

Pour consulter un media il faudra avoir eu son URL qui sera sous la forme [https://arvest-media.url/tfefjepzfzefzefzepfjzepz/monmedia.jpg](https://arvest-media.url/tfefjepzfzefzefzepfjzepz/monmedia.jpg)
Si l'URL n'est pas connu on peut raisonnablement considérer que le fichier est inacessible. Le nom du fichier est également conservé ce qui permet de le télécharger de manière simple.

ECRITURE (Création / remplacement / suppression)

L'écriture sera piloté depuis le front end MMU et effectué par le backend. L'écriture ne sera possible que par un utilisateur connecté à MMU et disposant des droits sur le média. Les droits seront gérés simplement par une liste d'utilisateur ayant les droits par média (concrétement une table en BDD)

- [x] #68
- [x] #69
- [x] #70
- [x] #71
- [x] #72
- [x] #74
- [x] #73
- [x] #75
- [x] #76
- [x] #77
- [x] #78
- [x] #79
- [x] #80
- [x] #81
- [x] #82
- [x] #83
- [x] #98

**Comment by geourjoa** [comment]
![image](https://github.com/SCENE-CE/mirador-multi-user/assets/122985699/7de68ad9-82fd-4d15-8b96-c8f5bbc30a22)

**Comment by geourjoa** [comment]
- [ ] Dessiner le schéma de BDD au propre : https://mermaid.live/
- [ ] Ajouter Caddy à la pile Docker
- [ ] Route d'API create media 
- [ ] Route d'API update media
- [ ] Route d'API delete media
- [ ] ROUTE d'API change right media 
- [ ] Implémenter la table média (id_media, path, id_creator, date_creation) 
- [ ] Implémenter les droits table link_media_user (id_user, id_media, right)
- [ ] Ajouter un menu media et une page media
- [ ] Liste des media de l'utilisateur et de ceux dont il a le droit 
- [ ] TO PRECISE (filtrer rechercher dans la liste)
- [ ] Voir un media 
- [ ] UI : upload un fichier 
- [ ] UI : reupload un fichier (remplacement)
- [ ] UI : Supprimer un média
- [ ] UI : Changer les droits du média (groupe d'user)
