### ISSUE TITLE
[Meta] Gestion des droits projets 

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-multi-user#51]
WIP Architecture

Mots clés : 
- URL de partage : attribut string d'un projet. Peut être nul. C'est un hash d'x caractères qui est unique en BDD. Exemple : [https://arvest.ttl.fr/sharing?url=efeijfezhfzefzejfezjfezfjzefezjfez](https://arvest.ttl.fr/efeijfezhfzefzejfezjfezfjzefezjfez)
-TODO préciser implementation des droits écriture lecture

Il y a 3 manières d’accéder à un projet MMU

1. Je suis le propriétaire du projet 
Fonctionnement actuel, c'est bon bon 

2. J'ai le droit d'édition ou de lecture car on m'a ajouté à liste des éditeurs de ce projet 
Dans la liste de mes projets, j'ai les projets qu'on m'a partagé.
Si je n'ai pas le droit d'écriture, je ne vois pas le bouton sauvegarder et MAE/MAEV sont désactivés.

3. On m'a partagé le projet par son URL de partage (en lecture uniquement donc)
- Je me connecte à l'URL de partage
- MMU détecte quel est le hash reçu via le paramètre URL.
   - l'URL reçu correspond à l'url d'un projet de la base -> MMU sert un mirador avec le state du projet. Il n'y a pas de possibilité de sauvegarde et un bandeau qui indique que les changements ne seront pas sauvegardé. Et MAE ou MAEV sont désactivés
   - l'URL reçu ne correspond pas à un projet de la base -> page d'erreur
   
- [x] #55
- [x] #56
- [x] #57
- [ ] #58

**Comment by geourjoa** [comment]
- [ ] ROUTE d'API change right project 
- [ ] Vérifier que la project correspond bien
- [ ] Implémenter les droits table link_group_project (id_user, id_group, right)
- UI : Changer les droits du projet (groupe d'user) -> reader / editor
