### ISSUE TITLE
[Meta] User group workflow

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-multi-user#66]
## Backend 

- [x]  When a user create a group his id is ad to the column 'userCreatorId'
- [x] #86
- [x]  A user can 'Read' a group without be part of it
- [x] #108
- [x] #110

## Frontend 

- [x] When user create a group it must add another user to it
- [x] To delete a group a user must had create it
- [x] To Update a Group a user must be part of it and it must still have at least 2 users inside of it
- [x] Implement UI following Groups rights 
- [x] User can search into group with proposition above search bar
- [x] #105
- [x] #106
- [x] #107
