### ISSUE TITLE
[Meta] Graphic Charter Integration

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-multi-user#84]
- [x] Font integration
- [x] Use picture from the graphic charter to design login page
- [ ] Design Footer with logos
- [ ] Create a theme for Mirador look for limits into Mirador's theming possibilities
- [ ] Transform MMU to be customizable and translatable 

Use this as an example : https://arvest.gitpages.huma-num.fr/
